project_name: mockingio

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: mockingio
    ldflags:
      - -s -w
      - -X github.com/mockingio/mockingio/cmd/version.Version={{.Version}}
      - -X github.com/mockingio/mockingio/cmd/version.Revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7

release:
  github:
    owner: mockingio
    name: mockingio

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^test:'
      - '^tests:'
      - '^ci:'
      - '^chore:'
      - '^refactor:'
      - "^Merge pull request"

brews:
  - tap:
      owner: mockingio
      name: mockingio-tap
    commit_author:
      name: tuongaz
      email: tuongaz@gmail.com
    homepage: "https://github.com/mockingio/mockingio"
    description: "mockingio is a mocking tool"
    test: |
      system "#{bin}/mockingio --version"

dockers:
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile.release
    use: buildx
    image_templates:
      - "mockingio/{{.ProjectName}}:latest"
      - "mockingio/{{.ProjectName}}:{{ .Tag }}"
      - "mockingio/{{.ProjectName}}:v{{ .Major }}"
    build_flag_templates:
      - "--platform=linux/arm64"
