project_name: smocky

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: smocky
    ldflags:
      - -s -w
      - -X github.com/smockyio/smocky/backend/version.Version={{.Version}}
      - -X github.com/smockyio/smocky/backend/version.Revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: tuongaz
      name: smocky
    commit_author:
      name: tuongaz
      email: tuongaz@gmail.com
    homepage: "https://github.com/tuongaz/smocky"
    description: "Smocky is a mocking tool"
    test: |
      system "#{bin}/smocky --version"