# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smocky < Formula
  desc "Smocky is a mocking tool"
  homepage "https://github.com/tuongaz/smocky"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.4/smocky_v0.0.4_darwin_arm64.tar.gz"
      sha256 "e48d4a572fbbef4e35f9b57650d8caa75db739b5247848a4b869afbd99017ffd"

      def install
        bin.install "smocky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.4/smocky_v0.0.4_darwin_amd64.tar.gz"
      sha256 "b825b085e17b71619a8acb37c8228eb3308e1bac21b34ca1b5ceeb8df2111c76"

      def install
        bin.install "smocky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.4/smocky_v0.0.4_linux_arm64.tar.gz"
      sha256 "a805cd32c221ceb8fd434bff8cd0f5c0c878c8a937fc89a71862ac7fa6a8a5e3"

      def install
        bin.install "smocky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.4/smocky_v0.0.4_linux_amd64.tar.gz"
      sha256 "ac35c605bd0e36e9dd4b716fb189e47997c5d312e35d09cd8af31a7d16b439af"

      def install
        bin.install "smocky"
      end
    end
  end

  test do
    system "#{bin}/smocky --version"
  end
end
