# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smocky < Formula
  desc "Smocky is a mocking tool"
  homepage "https://github.com/tuongaz/smocky"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.2/smocky_v0.0.2_darwin_arm64.tar.gz"
      sha256 "721370e074fd540dd3d095ed38a6c6b03f34389ba9a613c129d2e405ed0b1f26"

      def install
        bin.install "smocky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.2/smocky_v0.0.2_darwin_amd64.tar.gz"
      sha256 "364c80c0307957b442af5acf54e169a6c404a36428bc4580d6a26f4d8cd3a873"

      def install
        bin.install "smocky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.2/smocky_v0.0.2_linux_arm64.tar.gz"
      sha256 "a8ff850065e3c1885a9bb39578a7f62d93726b512cb2078f0541eb9c4aaddba9"

      def install
        bin.install "smocky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.2/smocky_v0.0.2_linux_amd64.tar.gz"
      sha256 "fb1ec4d09aa578a5e908bec812077771294663d860ed58d2e92d48e4cd443559"

      def install
        bin.install "smocky"
      end
    end
  end

  test do
    system "#{bin}/smocky --version"
  end
end
