# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smocky < Formula
  desc "Smocky is a mocking tool"
  homepage "https://github.com/tuongaz/smocky"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.3/smocky_v0.0.3_darwin_amd64.tar.gz"
      sha256 "9247bda3c0767f767826e1752224b8b5f410ee7204af865023b1bc795850b819"

      def install
        bin.install "smocky"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.3/smocky_v0.0.3_darwin_arm64.tar.gz"
      sha256 "0524bfd07090b122dc755d9ca03e019bda884b7d6e44cfca83755d9cfbb60827"

      def install
        bin.install "smocky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.3/smocky_v0.0.3_linux_amd64.tar.gz"
      sha256 "74f2c9d24c6a6b95ad67f99f05860384be3a8c2c4b83f4f99fb66dc804317f96"

      def install
        bin.install "smocky"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.3/smocky_v0.0.3_linux_arm64.tar.gz"
      sha256 "f35ff9694f4c7321840be1ac5d199631bd9c877e8a9f4d0bb5c21e8f6e661445"

      def install
        bin.install "smocky"
      end
    end
  end

  test do
    system "#{bin}/smocky --version"
  end
end
