version: '3'

tasks:
  server-test:
    dir: dagger
    cmds:
      - dagger do server_test --log-format=plain
  server-lint:
    dir: dagger
    cmds:
      - dagger do server_lint --log-format=plain
  build:
    dir: dagger
    cmds:
      - dagger do build --log-format=plain
  start:
    dir: backend
    cmds:
      - go run cmd/cli/main.go start --filename ./config/fixtures/mock.yml
  tidy:
    dir: backend
    cmds:
      - go mod tidy && go mod vendor && go mod download
  test:
    dir: backend
    cmds:
      - go test -v ./...

