version: '3'

tasks:
  backend:build:
    deps: [ lint, test ]
    cmds:
      - dagger do build --log-format=plain
  backend:start:
    cmds:
      - go run main.go start --filename ./example/mock.yml
  backend:start-with-admin:
    cmds:
      - go run main.go start --filename ./example/mock1.yml --filename ./example/mock2.yml  --admin
  backend:tidy:
    cmds:
      - go mod tidy && go mod vendor && go mod download
  backend:lint:
    cmds:
      - dagger do lint --log-format=plain
  backend:test:
    cmds:
      - dagger do test --log-format=plain
  frontend:start:
    dir: frontend
    cmds:
      - npm run dev

