version: '3'

tasks:
  build:
    deps: [ lint, test ]
    cmds:
      - dagger do build --log-format=plain
  dev:
    cmds:
      - go run main.go start --filename ./testdata/mock1.yml --filename ./testdata/mock2.yml --persist
  tidy:
    cmds:
      - go mod tidy && go mod vendor && go mod download
  lint:
    cmds:
      - dagger do lint --log-format=plain
  test:
    cmds:
      - dagger do test --log-format=plain

