name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dagger
        run: |
          if ! command -v dagger &> /dev/null
          then
            cd /usr/local && curl -L https://dl.dagger.io/dagger/install.sh | sh
          fi
      - name: Dagger
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            do test